### ISSUE TITLE
Get all File and Folder notification using SCEvents (FSEvents wrapper )?

### ISSUE THREAD

**Issue by Bhushan30** [mz2/SCEvents#1]
I had implemented file watcher part using SCEvents : https://github.com/mz2/SCEvents It is notifying all changes. But I want only file created, deleted, renamed, modified events notification and also folder created,deleted,renamed notification? How to get exact these notification? And How to used it? I don't need all notification.

output I get is this:

2014-02-12 13:09:14.607 TestSCEvent10-2[5189:503] SCEvent { eventId = 3348870, eventPath = /Users/user1/.Trash/untitled folder 1.09.13 PM, eventFlags = 133120 }
Its notifying me changed in the form of event_id, event_path and event_flags. But how should I get information which event is raise. Its not giving any details like File created event occurs, File Renamed event occur etc.

How should i get proper information about which event is raised?
Can we get notification type(like file created, file deleted etc.) using eventFlags? or is there any other way for this?

Please give me direction. Thanks...

**Comment by mz2** [comment]
The event flags contain the information that you can use to make conditional behaviours with: http://stackoverflow.com/questions/13699812/is-there-a-definitive-list-of-fsevents-event-flags
