### ISSUE TITLE
Returning different value of _eventsFlags in SCEvents(FSEvents wrapper )?

### ISSUE THREAD

**Issue by Bhushan30** [mz2/SCEvents#2]
I implemented file watcher part using SCEvents
Its giving output like this :

2014-02-11 16:08:38.725 TestSCEvent10-2[2995:403] 
SCEvent { 
          eventId = 3182336, 
          eventPath = /Users/user1/Desktop, 
          eventFlags = 131328 
        }
Value of enum is :

kFSEventStreamEventFlagItemCreated       = 0x00000100,
kFSEventStreamEventFlagItemRemoved       = 0x00000200,
kFSEventStreamEventFlagItemInodeMetaMod  = 0x00000400,
kFSEventStreamEventFlagItemRenamed       = 0x00000800,
kFSEventStreamEventFlagItemModified      = 0x00001000,
kFSEventStreamEventFlagItemFinderInfoMod = 0x00002000,
kFSEventStreamEventFlagItemChangeOwner   = 0x00004000,
kFSEventStreamEventFlagItemXattrMod      = 0x00008000,
kFSEventStreamEventFlagItemIsFile        = 0x00010000,
kFSEventStreamEventFlagItemIsDir         = 0x00020000,
kFSEventStreamEventFlagItemIsSymlink     = 0x00040000

It register SCEvents flags with above value, and If we run the application and change the file contents or renamed the file the value of _eventsFlags is different. So i unable to know which file event is occured?

Please provide me direction...

**Comment by mz2** [comment]
@Bhushan30 it's an option mask: http://stackoverflow.com/questions/2555101/how-do-those-bitmasks-actually-work
