### ISSUE TITLE
Getting a warning: SCEvent.m:110:1: Method possibly missing a [super dealloc] call

### ISSUE THREAD

**Issue by agerson** [mz2/SCEvents#4]

**Comment by agerson** [comment]
The error is on:

```
- (void)dealloc
{
    _eventDate = nil;
}
```

**Comment by mz2** [comment]
Sounds like you are using a very old SDK (pre-OSX 10.7?) to compile SCEvent.m. I've just pushed a framework target in the repo to make integrating with it easier.
